apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
stringData:
  AWS_SECRET_ACCESS_KEY: "Kz3EKDf9+YGC/avef2bkQPaA8USIfbg552mY4tqv"
  AWS_ACCESS_KEY_ID: "AKIARWFGSILTV6N4FJ7F"
  AWS_ACCOUNT: {{ .Values.image.aws | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-registry-helper-cm
data:
  AWS_REGION: {{ .Values.image.region }}
  DOCKER_SECRET_NAME: regcred
