apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: {{ .Values.deployment.replicas}}       #3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.image.aws}}.dkr.ecr.{{ .Values.image.region}}.amazonaws.com/devopsproject
        #116313440999.dkr.ecr.eu-central-1.amazonaws.com/devopsproject:latest  
        #116313440999.dkr.ecr.eu-central-1.amazonaws.com/devopsproject  
        #116313440999.dkr.ecr.eu-central-1.amazonaws.com/devopsproject
        imagePullPolicy: Always
        ports:
          - name: web
            containerPort: 8081
      imagePullSecrets:
          - name: regcred
